### ISSUE TITLE
[BUG] Spotify notification buttons don't work

### ISSUE THREAD

**Issue by Shorakie** [Crylia/crylia-theme#10]
**Describe the bug**
Pressing the buttons (prev, play/pause, next) of spotify notification cuases the notification to disapear instead of doing the right action.

**To Reproduce**
1. fresh install of the theme

**Expected behavior**
Buttons should not close the notification and instead they should do their corresponding action (prev, play/pause, next). also i think the notification timer should freeze when user is intracting with the buttons for some seconds.

**Screenshots**
![image_2022-05-18_143743073](https://user-images.githubusercontent.com/24689604/169014849-f7db2244-988a-4835-91d0-622c7336182e.png)

**Information:**
 - Distro Arch
 - Awesome v4.3-1360-gc539e0e4

**Additional Context**
im using the AUR version of spotify and not the flatpack version

**Comment by Shorakie** [comment]
after reading the source code i noticed i didn't have the `playerctl` package installed. installing the package fixed the issue.
however its nice to pause the timer of notification whenever the mouse is hovering it or intracting with actions

**Comment by Crylia** [comment]
@Shorakie That might be a good idea. I also plan to open and or focus an application once you left click on it.

BTW the playerctl is noted in the new README.md [here](https://github.com/Crylia/crylia-theme#playerctl---media-control)

I'm gonna throw this in here since it's gonna pop up as an issue at some point:
The notification buttons won't work when you skipped a song with your media control keys or in spotify directly while one notification is still active. Spotify basically overrides the old notification and thanks to that its broken. You can see that when the title has no color anymore and the timeout is not correct anymore.
