### ISSUE TITLE
[BUG] Inconsistent dock behavior between 1080p and 2160p

### ISSUE THREAD

**Issue by Vantazz** [Crylia/crylia-theme#12]
**Describe the bug**
On my 4k TV the activation area for the dock shows through fullscreen content, such as mpv or firefox.

**To Reproduce**
xrandr to switch to only the 4k tv, then fullscreen something

**Expected behavior**
Content should show above the dock area

**Screenshots**
![image](https://user-images.githubusercontent.com/31926730/169194519-7149c6bd-2d2d-43f2-96e2-4a8444abd7ab.png)

**Information (please complete the following information):**
Arch
awesome v4.3-1360-gc539e0e43

**Comment by Crylia** [comment]
Do you use your own picom conf? I think I had this happen once too, but I'm actually unsure on how I resolved this.

**Comment by Shorakie** [comment]
I also had the same issue, alongside the dock window down bellow my volume osd, rofi, etc had the same issue of showing wrong background. 

The issue turned out to be that i didn't have picom installed and properly configured. after doing so fixed the issue.

Make sure picom is running using `htop` or this command `ps -A | grep picom`.

**Comment by Crylia** [comment]
Glad it got resolved, if there is nothing else regarding this, then I'm going to close this.
