### ISSUE TITLE
Failed to get gpu temp

### ISSUE THREAD

**Issue by Shardj** [Crylia/crylia-theme#23]
.config/awesome/src/widgets/gpu_info.lua:119: attempt to compare nil with number

Debugging:

    bash -c "nvidia-smi -q -d TEMERATURE"

gives me

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

I currently have the proprietary tested  nvidia-driver-510 installed

**Comment by Crylia** [comment]
It because you wrote TEM**P**ERATURE without the P.
But assuming that was just a typo here and its correct in the config then its a really weird Issue. I use the same driver btw.
Can you confirm that Nvidia supports your GPU with this driver/nvidia-smi tool?
`bash -c "nvidia-smi -q -d TEMPERATURE | grep 'GPU Current Temp' | awk '{print $5}'"` Works fine for me

Nonetheless I'm going to add a nil check since AMD folks might get the same error.

**Comment by Shardj** [comment]
Yeah it's correct in the config, that was just a typo from me copying it down

**Comment by Shardj** [comment]
But yeah, this

    bash -c "nvidia-smi -q -d TEMPERATURE | grep 'GPU Current Temp' | awk '{print $5}'"

gives no output since

    bash -c "nvidia-smi -q -d TEMPERATURE"

gives "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."

**Comment by Shardj** [comment]
I'll try re-installing my nvidia drivers at a later date. I won't do it this week since I can't afford to screw up my computer right now

**Comment by Crylia** [comment]
Good luck with that. Drivers (especially Nvidia) can be a huge pain
