### ISSUE TITLE
[BUG] Battery dont show correctly

### ISSUE THREAD

**Issue by ghost** [Crylia/crylia-theme#48]
Hello my Battery Widget dont show correctly 

i tried this but dont work
https://github.com/Crylia/crylia-theme/issues/18

**Comment by Crylia** [comment]
What exactly is shown? Also can you give me the output from the command in the battery widget?

**Comment by ghost** [comment]
> What exactly is shown? Also can you give me the output from the command in the battery widget?

**Comment by ghost** [comment]
https://i.imgur.com/QTSe0Gg.png

**Comment by ghost** [comment]
This is my init.lua

-- Awesome Libs
local awful = require("awful")

awful.screen.connect_for_each_screen(
-- For each screen this function is called once
-- If you want to change the modules per screen use the indices
-- e.g. 1 would be the primary screen and 2 the secondary screen.
  function(s)
  -- Create 9 tags
  awful.layout.layouts = user_vars.layouts
  awful.tag(
    { "1", "2", "3", "4", "5", "6", "7", "8", "9" },
    s,
    user_vars.layouts[1]
  )

  require("src.modules.powermenu")(s)
  -- TODO: rewrite calendar osd, maybe write an own inplementation
  -- require("src.modules.calendar_osd")(s)
  require("src.modules.volume_osd")(s)
  require("src.modules.brightness_osd")(s)
  require("src.modules.titlebar")
  require("src.modules.volume_controller")(s)

  -- Widgets
  s.battery = require("src.widgets.battery")()
  s.audio = require("src.widgets.audio")(s)
  s.date = require("src.widgets.date")()
  s.clock = require("src.widgets.clock")()
  s.bluetooth = require("src.widgets.bluetooth")()
  --s.layoutlist = require("src.widgets.layout_list")(s)
  s.powerbutton = require("src.widgets.power")()
  --s.kblayout = require("src.widgets.kblayout")(s)
  s.taglist = require("src.widgets.taglist")(s)
  s.tasklist = require("src.widgets.tasklist")(s)
  --s.cpu_freq = require("src.widgets.cpu_info")("freq", "average")

  -- Add more of these if statements if you want to change
  -- the modules/widgets per screen.
  if s.index == 1 then
    s.systray = require("src.widgets.systray")(s)
    s.cpu_usage = require("src.widgets.cpu_info")("usage")
    s.cpu_temp = require("src.widgets.cpu_info")("temp")
    s.gpu_usage = require("src.widgets.gpu_info")("usage")
    s.gpu_temp = require("src.widgets.gpu_info")("temp")

    require("crylia_bar.left_bar")(s, { s.layoutlist, s.systray, s.taglist })
    require("crylia_bar.center_bar")(s, { s.tasklist })
    require("crylia_bar.right_bar")(s, { s.gpu_usage, s.gpu_temp, s.cpu_usage, s.cpu_temp, s.audio, s.kblayout, s.date, s.clock, s.powerbutton })
    require("crylia_bar.dock")(s, user_vars.dock_programs)
  end

  if s.index == 2 then
    s.network = require("src.widgets.network")()
    s.ram_info = require("src.widgets.ram_info")()

    require("crylia_bar.left_bar")(s, { s.layoutlist, s.taglist })
    require("crylia_bar.center_bar")(s, { s.tasklist })
    require("crylia_bar.right_bar")(s, { s.ram_info, s.audio, s.kblayout, s.network, s.date, s.clock, s.powerbutton })
  end
end
)

**Comment by georgeswan** [comment]
The reason is because, the battery widget hasn't been added to your wibar.

You have the battery widget un-commented in the init.lua,  which is good,  you just needed to add it to the list of widgets for screen 1 (and 2 if you want) in:
 `require("crylia_bar.right_bar")(s, { s.gpu_usage, s.gpu_temp, s.cpu_usage, s.cpu_temp, s.audio, s.kblayout, s.date, s.clock, s.powerbutton })`

In the image you provided there was no battery widget on the right bar ( you probably got confused with the gpu usage widget).  It should look something like this (except yours will have different colours) [Right bar](https://imgur.com/gallery/wSBaiLu)

**To add the battery widget:**

For screen 1 just add `s.battery ` to  `require("crylia_bar.right_bar")(s, { s.gpu_usage, s.gpu_temp, s.cpu_usage, s.cpu_temp, s.audio, s.kblayout, s.date, s.clock, s.powerbutton })` Where you put it is up to you, however it determines where on the bar it is, for example if its the first entry on the list it will be the left most widget on the bar.

**Here is the example code for the battery widget with it as the left most widget (next to the gpu widget) on screen 1:**

`require("crylia_bar.right_bar")(s, { s.battery, s.gpu_usage, s.gpu_temp, s.cpu_usage, s.cpu_temp, s.audio, s.kblayout, s.date, s.clock, s.powerbutton })`

**For screen 2 if you want the battery widget there aswell (left most widget again):**

`require("crylia_bar.right_bar")(s, {s.battery, s.ram_info, s.audio, s.kblayout, s.network, s.date, s.clock, s.powerbutton })`

Hope this helps!

**Comment by ghost** [comment]
> The reason is because, the battery widget hasn't been added to your wibar.
> 
> You have the battery widget un-commented in the init.lua, which is good, you just needed to add it to the list of widgets for screen 1 (and 2 if you want) in: `require("crylia_bar.right_bar")(s, { s.gpu_usage, s.gpu_temp, s.cpu_usage, s.cpu_temp, s.audio, s.kblayout, s.date, s.clock, s.powerbutton })`
> 
> In the image you provided there was no battery widget on the right bar ( you probably got confused with the gpu usage widget). It should look something like this (except yours will have different colours) [Right bar](https://imgur.com/gallery/wSBaiLu)
> 
> **To add the battery widget:**
> 
> For screen 1 just add `s.battery ` to `require("crylia_bar.right_bar")(s, { s.gpu_usage, s.gpu_temp, s.cpu_usage, s.cpu_temp, s.audio, s.kblayout, s.date, s.clock, s.powerbutton })` Where you put it is up to you, however it determines where on the bar it is, for example if its the first entry on the list it will be the left most widget on the bar.
> 
> **Here is the example code for the battery widget with it as the left most widget (next to the gpu widget) on screen 1:**
> 
> `require("crylia_bar.right_bar")(s, { s.battery, s.gpu_usage, s.gpu_temp, s.cpu_usage, s.cpu_temp, s.audio, s.kblayout, s.date, s.clock, s.powerbutton })`
> 
> **For screen 2 if you want the battery widget there aswell (left most widget again):**
> 
> `require("crylia_bar.right_bar")(s, {s.battery, s.ram_info, s.audio, s.kblayout, s.network, s.date, s.clock, s.powerbutton })`
> 
> Hope this helps!

Yes i know i make a Post yesterday with that fix 
but Thanks ;) 

here is the Post https://github.com/Crylia/crylia-theme/issues/49
